class Project {
  final String name;
  final String description;
  final String image;
  final String link;
  final List<String>? tags;
  final int? stars;
  Project(
      {required this.name,
      required this.description,
      required this.image,
      required this.link,
      this.tags,
      this.stars});
}

List<Project> projectList = [
  Project(
      name: "ChatGPT-Tauri",
      description:
          "ChatGPTxTauri is a desktop application that allows users to interact with a large language model based on GPT-3.5 architecture. Available on macOS, Linux, and Windows operating systems, the app provides users with a chat interface where they can input text and receive responses generated by the AI model.",
      image: "image",
      link: "https://github.com/TESLA2402/ChatGPT-Tauri",
      stars: 3,
      tags: [
        "Tauri",
        "Rust",
        "NextJs",
        "TypeScript",
        "Desktop-application",
        "windows",
        "macos"
      ]),
  Project(
      name: "Supabase_Flutter",
      description:
          "An application that displays news articles, sorts them on the basis of their categories, and can save your favourite articles.",
      image: "image",
      link: "https://github.com/TESLA2402/Supabase_Flutter",
      stars: 2,
      tags: ["flutter", "supabase-auth", "supabase-db", "supabase-storage"]),
  Project(
      name: "Manas_Kriti_Software_PS",
      description:
          "An application (mobile app) which can be used by the local residents to check if a particular shop is open right now or not, what is its menu / services list and an option to place an order directly.",
      image: "image",
      link: "https://github.com/TESLA2402/Manas_Kriti_Software_PS",
      stars: 3,
      tags: ["Flutter", "Firebase"]),
  Project(
      name: "Meeting-Platform",
      description:
          "The platform will provide features such as audio and video conferencing, screen sharing, chat, and file sharing. The platform is designed to be user-friendly and accessible, allowing individuals and teams to easily connect and collaborate from anywhere in the world.",
      image: "image",
      link: "https://github.com/TESLA2402/Meeting-Platform",
      stars: 0,
      tags: ["JavaScript", "NodeJs", "expressJs"]),
  Project(
      name: "ChatBox",
      description:
          "a real-time chat application using Flutter and Firebase in which two users can chat in realtime. App also includes a chatbot which which will generate smart replies to the user’s message.",
      image: "image",
      link: "https://github.com/TESLA2402/chatapp",
      stars: 2,
      tags: ["flutter", "firebase"])
];
